site_name: Antares
theme:
  name: material

nav: [
        "home": "index.html",
        "Escopo": [
          "documentos/declaracao de escopo/declaracao_de_escopo.md"
        ],
        "Visão do Produto e Projeto": [
            "documentos/visao de produto e projeto/produto_e_projeto.md"
        ],

]
