site_name: Unb na Mão - Antares

theme:
  palette:

    # Light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/theme-light-dark
        name: Mudar para o tema escuro

    # Dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/theme-light-dark
        name: Mudar para o tema claro

  language: pt
  name: material

copyright: Copyright &copy; 2023 - 2023 UnB na Mão


nav: [
  "Home": "index.md",
  "Visão do Produto e Projeto": "visao_do_produto_e_projeto/documento_de_visao_do_produto_e_projeto.md",
  "Declaração de Escopo": "escopo/documento_de_escopo.md",
  "Arquitetura": "arquitetura/documento_de_arquitetura.md"
    
]
