site_name: Unb na Mão - Antares


nav: [
  "Home": "index.html",
  "Entregas": [
    "documento_de_visao_do_produto_e_projeto.md",
    "documento_de_escopo.md",
    "documento_de_arquitetura.md"
  ],  
]
